# Generated by Django 4.2.9 on 2024-01-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField()),
                ('image', models.ImageField(upload_to='place_images/')),
            ],
        ),
    ]
